board:
  name: keys60
  vendor: sig
  socs:
    - name: nrf52840
  revision:
    format: custom
    default: rev_ansi62_rot
    revisions:
      - name: rev_ansi62_rot
      - name: rev_ansi61
      - name: rev_ansi61_rot
      - name: rev_ansi64
